### ISSUE TITLE
P2 movie is about cocos2d and spritebuilder not spritekit

### ISSUE THREAD

**Issue by AnnMic** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift#13]
The movie on the section "2. SpriteKit and Scene Editor" is about cocos2d and spritebuilder not Spritekit.

**Comment by AnnMic** [comment]
I know there is a note for this but thought it might be good with an issue as well so its not missed.

**Comment by dionlarson** [comment]
Thank you! Slides have been rewritten by @cocojoe -- I'll be rerecording the audio later this week.

**Comment by dionlarson** [comment]
Closed for now, will re-add after re-record.
