### ISSUE TITLE
P4 Typo

### ISSUE THREAD

**Issue by zontan** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift#15]
Under creating the seal scene - "The process to add our cute but evil seal's" - no apostrophe needed here.

**Comment by zontan** [comment]
Under seal physics - "You will also want to be alerted when the seal is involved in a collision with anything so you set the Contact Mask to 1." - but setting the contact mask to 1 only tells you about contacting category 1 (the penguin) not 'anything'.

**Comment by zontan** [comment]
Also, the summary list is messed up here too.

**Comment by AnnMic** [comment]
there is a "?" in the middle of this sentence as well; However, it does for other objects like the ?penguin which I will discuss later.
