### ISSUE TITLE
p10 Getting the physics bodies ready

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift#17]
I made it to this section and it seems that catapult was not defined. I can't find where this for a value. I needed to include: 

```
/* Catapult */
catapult = childNodeWithName("catapult") as! SKSpriteNode
```

**Comment by cocojoe** [comment]
So yeah, I've checked this and can't see it, I see catapultArm mentioned earlier but not catapult. I thought it might just say 'please add a code connection yourself', couldn't see that either.

**Comment by cocojoe** [comment]
It is there just not as obvious, made it into an action
