### ISSUE TITLE
P10 Missing declaration and definition for 

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift#20]
Under heading: Dat first joint :]

At this stage I get an error unless I add 

`var cantileverNode: SKSpriteNode!`

and 

```
/* cantileverNode */
cantileverNode = childNodeWithName("cantileverNode") as! SKSpriteNode
```

**Comment by cocojoe** [comment]
You sure? cantileverNode is not mentioned until later in the tutorial...

**Comment by soggybag** [comment]
It's mentioned later.
