### ISSUE TITLE
P10 Image inconsistency

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift#21]
The last image under the heading: Dat first joint :] doesn't show the red square as the node. This might be confusing. Especially when the read square appears in their code. In later steps this square appears again.

**Comment by cocojoe** [comment]
When the game runs, the red node doesn't show

**Comment by soggybag** [comment]
I feel it will confuse students if the image in the tutorial doesn't match what they are seeing.
