### ISSUE TITLE
400 is too big of a mutiplier

### ISSUE THREAD

**Issue by esscbee** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift#23]
On "7. Building the game scene" there's a 400 multiplier.  On my iPhone 5s, the penguins fly off the screen so fast, I can't even seen them.   10 works well on my phone.

**Comment by john-b-yang** [comment]
Haha these penguins are going at light speed >_<

**Comment by esscbee** [comment]
Making them nearly invisible!
