### ISSUE TITLE
P11 Problem in code sample

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift#24]
Seems this code snippet:

```
let resourcePath = NSBundle.mainBundle().pathForResource("Penguin", ofType: "sis")
let penguin = MSReferenceNode(URL: NSURL (fileURLWithPath: resourcePath!))
```

Should read: 
`let penguin = MSReferenceNode(fileNamed: "Penguin")`

**Comment by cocojoe** [comment]
No, in theory it should be, in practice there is a bug in Xcode 7.3.  This is the workaround. More info:

https://stackoverflow.com/questions/36388900/add-skreferencenode-programmatically/36971712
