### ISSUE TITLE
P3 Use gif to show bear animation

### ISSUE THREAD

**Issue by davichaves** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift#27]
<img width="1020" alt="screen shot 2016-06-13 at 2 26 25 pm" src="https://cloud.githubusercontent.com/assets/7053287/16023705/e0d25340-3172-11e6-8d1e-310373a28fac.png">

**Comment by cocojoe** [comment]
#29 
Although you reported first I read #29 first and have already commented.
