### ISSUE TITLE
P4 minor issue image is not animated

### ISSUE THREAD

**Issue by AnnMic** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift#29]
The text states this;  Great job, time to press Animate at the top of the timeline editor and your bear should hopefully look like this:

But the image is a static image of the bear. Would be nice if the arms were moving

**Comment by cocojoe** [comment]
@dionlarson the original file `bear_arm.gif` is an animated gif, is there some magic going on during the web process?

**Comment by dionlarson** [comment]
Gif was not created as a looping gif. Fixed in b420c02.
