### ISSUE TITLE
P?? catapultSpringJoint.frequency missing? 

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift#37]
I ended the tutorial without: 

`catapultSpringJoint.frequency = 1.5`

I went back and searched the tutorial pages and could't this anywhere. I might have missed it. I got this from comparing my project with the completed project. I may have missed this.

**Comment by AnnMic** [comment]
I cannot find it either it should be somewhere in P10
