### ISSUE TITLE
P06 Typos

### ISSUE THREAD

**Issue by zontan** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift#41]
"drag the Bear.sks from the Project Navigator scene" - the Project Navigator is not a scene.

**Comment by zontan** [comment]
Penguin Launcher model 1 - "SpriteKit doesn't include any handy vector maths libraries out of the box, thankfully the internet tends provide" - tends to\* provide

**Comment by zontan** [comment]
Just below: "Time for your to connect the catapult arm, spawn penguins and launch them into the stratosphere."

**Comment by zontan** [comment]
"see how many penguins can you add ?"

**Comment by zontan** [comment]
"Next you multiple this by 10"

**Comment by cocojoe** [comment]
You doing a pull for this?

**Comment by zontan** [comment]
Summary:

Build a simple game scene
Construct a simple catapult
Dynamically adding new penguins to the scene
Applying impulse in a specific direction to launch the penguin

Tense change again

**Comment by zontan** [comment]
@cocojoe Yep
