### ISSUE TITLE
P06 CGPoint extension not working

### ISSUE THREAD

**Issue by zontan** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift#42]
This line: "penguin.avatar.position = catapultArm.position + CGPoint(x: 32, y: 50)" is failing to compile. I'm  not entirely sure why, since I've added the SKTUtils to my project and can personally find the CGPoint + CGPoint method, but apparently Xcode can't.

**Comment by AnnMic** [comment]
I had to remove all the files and add them without the parent folder. Then put them into a folder. This worked for me.

**Comment by zontan** [comment]
The fact that that worked for you gave me an idea, and I was right - you need to make sure you select 'create group' instead of 'create folder references'. It's possible this should be mentioned in the tutorial.
