### ISSUE TITLE
P06 Launching MainScene - Naming issue

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift#5]
Seems there is discrepancy in naming "MainMenu" vs "MainScene" when I get to this step I need to use: 

if let scene = MainScene(fileNamed:"MainMenu") {

The text here says: 

if let scene = GameScene(fileNamed:"MainScene") {

**Comment by soggybag** [comment]
This issue propagates through the example, you might change the file name earlier in the example.

**Comment by cocojoe** [comment]
Was fixed in another issue, although you did report first :)
