### ISSUE TITLE
P07 Missing image for solution adding ground physics

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift#8]
Broken image inside the show solution box under the heading: Ground physics

**Comment by cocojoe** [comment]
Looks fine in atom, screenshot please

**Comment by soggybag** [comment]
I was viewing the tutorial from the makeschool web Site with safari

**Comment by cocojoe** [comment]
screenshot please
